### ISSUE TITLE
a question about Unsupervised Training part

### ISSUE THREAD

**Issue by LanCole** [benesakitam/MHCL#1]
In readme Unsupervised Training part:
python main_moco.py \
  -a resnet50 \
  --lr 0.015 \
  --batch-size 128 \
  --epochs 800 \
  --mlp --moco-t 0.2 --aug-plus --cos \
  --mhcl --a 1.0 --b 0.1 \
  --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0 \
  [your mlrsnet(4:6)-folder with train and val folders]

I didn't find the main_moco.py file in the folder, should we change main_moco to main_mhcl. py?
Thanks.

**Comment by benesakitam** [comment]
Thank you for your interest in our work. You are right, please use main_mhcl.py. we will fix this small bug on our github page.
